export const SHOWCASE_LIST_REQUEST = "SHOWCASE_LIST_REQUEST";
export const SHOWCASE_LIST_SUCCESS = "SHOWCASE_LIST_SUCCESS";
export const SHOWCASE_LIST_FAIL = "SHOWCASE_LIST_FAIL";

export const SHOWCASE_CREATE_REQUEST = "SHOWCASE_CREATE_REQUEST";
export const SHOWCASE_CREATE_SUCCESS = "SHOWCASE_CREATE_SUCCESS";
export const SHOWCASE_CREATE_FAIL = "SHOWCASE_CREATE_FAIL";
export const SHOWCASE_CREATE_RESET = "SHOWCASE_CREATE_RESET";

export const SHOWCASE_DELETE_REQUEST = "SHOWCASE_DELETE_REQUEST";
export const SHOWCASE_DELETE_SUCCESS = "SHOWCASE_DELETE_SUCCESS";
export const SHOWCASE_DELETE_FAIL = "SHOWCASE_DELETE_FAIL";

export const SHOWCASE_DETAILS_REQUEST = "SHOWCASE_DETAILS_REQUEST";
export const SHOWCASE_DETAILS_SUCCESS = "SHOWCASE_DETAILS_SUCCESS";
export const SHOWCASE_DETAILS_FAIL = "SHOWCASE_DETAILS_FAIL";
export const SHOWCASE_DETAILS_RESET = "SHOWCASE_DETAILS_RESET";

export const SHOWCASE_UPDATE_REQUEST = "SHOWCASE_UPDATE_REQUEST";
export const SHOWCASE_UPDATE_SUCCESS = "SHOWCASE_UPDATE_SUCCESS";
export const SHOWCASE_UPDATE_FAIL = "SHOWCASE_UPDATE_FAIL";
export const SHOWCASE_UPDATE_RESET = "SHOWCASE_UPDATE_RESET";
