export const SHOWCASE_LIST_REQUEST = "SHOWCASE_LIST_REQUEST";
export const SHOWCASE_LIST_SUCCESS = "SHOWCASE_LIST_SUCCESS";
export const SHOWCASE_LIST_FAIL = "SHOWCASE_LIST_FAIL";

export const SHOWCASE_CREATE_REQUEST = "SHOWCASE_CREATE_REQUEST";
export const SHOWCASE_CREATE_SUCCESS = "SHOWCASE_CREATE_SUCCESS";
export const SHOWCASE_CREATE_FAIL = "SHOWCASE_CREATE_FAIL";
export const SHOWCASE_CREATE_RESET = "SHOWCASE_CREATE_RESET";
